name: Generate Lunch JSON

on:
  schedule:
    - cron: '0 3 * * *' # KÃ¶r varje dag 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Generate lunch JSON
        run: npm run generate

      - name: Commit & push PNG to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B gh-pages
          git add lunchuppdala.png
          git commit -m "updated lunch json"
          git push -f origin gh-pages
